export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY";
export const INVALID_DATA = "INVALID_DATA";
export const RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";